FROM golang:1.21 AS builder

WORKDIR /app

COPY ../go.mod ../go.sum ./
RUN go mod download

COPY .. .

RUN go build -o client ./client/client.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/client .

CMD ["./client"]