FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o client ./client

FROM golang:latest

WORKDIR /app

COPY --from=builder /app/client .

CMD ["./client"]
