services:
  server1:
    build:
      context: .
      dockerfile: server1/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - app-network

  server2:
    build:
      context: .
      dockerfile: server2/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server1
      - server2
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge