FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o server2 ./server2

FROM golang:latest

WORKDIR /app

COPY --from=builder /app/server2 .

CMD ["./server2"]
