FROM golang:1.21 AS builder

WORKDIR /app

COPY ../go.mod ../go.sum ./
RUN go mod download

COPY .. .

RUN go build -o server2 ./server2/server2.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/server2 .

EXPOSE 8081

CMD ["./server2"]