FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o server1 ./server1

FROM golang:latest

WORKDIR /app

COPY --from=builder /app/server1 .

CMD ["./server1"]
